spring:
  thymeleaf:
#    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  profiles:
    active: dev
  security:
    user:
      password: 111
      name: 111

comment.avater: /images/avatar.png




