spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjlroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  redis:
    host: 1.117.172.61
    port: 6379
    database: 0
logging:
  level:
    root: warn
    com.jack_wang: info
  file:
    path: log/blog-pro.log
server:
  port: 8080


