version: "3.0"
services:
  app:
    build:
      context: ./blog
      dockerfile: Dockerfile
    container_name: app
    ports:
    - "80:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=wjlroot

